### ISSUE TITLE
Feature request: Mark as spam

### ISSUE THREAD

**Issue by Bernd95** [justreportit/thunderbird#10]
It would be cool if the addon first marks an email as spam in case it is not already marked. That would save one more click for the user and also train the spam filter.

**Comment by nicprov** [comment]
This is a good suggestion! I'll definitely be adding this in the next release! I'll keep the issue open until then.

**Comment by nicprov** [comment]
This feature has been added in the latest release. If there are any issues with the release, please open a new Github issue!

**Comment by Bernd95** [comment]
I was hoping to get this option not as an alternative to deleting the message but as an additional step. So: Send message, mark as spam (to train the spam filter), delete it. Maybe you can have a checkbox for "Mark as junk" and redio buttons for no action/delete/trash. 
By the way, if you need the German translation for the new option: "Mark as Junk" can be translated as "Als Spam markieren" in German.

**Comment by nicprov** [comment]
@Bernd95 You are right. I just released a change (v1.2.1) which automatically marks it as junk (no need to select it in the menu). This action is done in addition to whatever you selected in the options menu (Delete it, move it, etc.). I hope this satisfies your request!
