### ISSUE TITLE
Feature request. Treat several messages at once

### ISSUE THREAD

**Issue by Bernd95** [justreportit/thunderbird#11]
It would be cool if I could mark several message and JustReportIt would report them all at once. I am not sure if this works for all reporting options (since I don't understand them) but for SpamCop it would work for sure.

**Comment by nicprov** [comment]
Yes I agree. I left this feature out at first because it was little time consuming to implement, but now that I have a little more time, I should be able to tackle this shortly. I'll keep this issue open until then.

**Comment by nicprov** [comment]
This has been added in the latest release. If there are any issues with the release, please open a new Github issue!
