### ISSUE TITLE
Lookup abuse records via abuse.net

### ISSUE THREAD

**Issue by mss** [justreportit/thunderbird#23]
It would be useful if the plugin could not only look up the address of the registrar but also of the senders' domain abuse contact. For example, for gmail.com adresses the registrar address will be abusecomplaints@markmonitor.com but the actual report address is abuse@gmail.com.

abuse.net provides a means of finding the correct contact address. The DNS based API is documented here https://www.abuse.net/using.phtml

Since AFAIK the Addon API doesn't support querying TXT records (at least https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve doesn't show any option to do so) I guess this would have to go through the API backend as well.

**Comment by nicprov** [comment]
This is interesting, however, this seems to be the exact purpose of SpamCop (https://www.spamcop.net/), which is actually the main use case for this add-on.

The issue with lookups is that they are often time-consuming (especially while reporting a lot of emails), this is why this process is currently being deferred to SpamCop. Do you see a particular use-case where this could be useful?
