### ISSUE TITLE
Reporting opens a blank email with no to address?

### ISSUE THREAD

**Issue by LiamDawe** [justreportit/thunderbird#30]
First time using this extension and there's no real instructions on how it works.

When reporting, it throws up a new email with the attachement but there's no email in the "To" field. Do I need to manually send it somewhere, I thought the point of the extension was to do it for you?

**Comment by nicprov** [comment]
@LiamDawe please email our support (support@justreport.it) for help on how to use the extension. We will gladly help you from there!
