### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by moi90** [justreportit/thunderbird#37]
It would be great to have a some documentation which describes the different options. Maybe a GitHub Wiki is sufficient?

In my case: What is "Quick-SpamCop"?

**Comment by nicprov** [comment]
@moi90 I agree, this is in my todo list. 

To answer your question however, the "Enable Quick SpamCop" option changes the reporting email from _**submit**.{spamcop_id}@spam.spamcop.net_ to _**quick**.{spamcop_id}@spam.spamcop.net_

The difference is highlighted [here](https://forum.spamcop.net/topic/163-faq-entry-what-is-quick-reporting/), but to sum up, quick reporting is used to report more quickly. It only looks at the source and ignores the body.

**Comment by moi90** [comment]
Thanks for the explanation!

**Comment by nicprov** [comment]
@moi90 I've created the wiki. It's a little lean at the moment, but I'll update it as I receive questions from people. For that reason, I'll mark this issue as resolved.

**Comment by moi90** [comment]
Great, thanks!

**Comment by nicprov** [comment]
@LionelHolt Here's the link: https://github.com/justreportit/thunderbird/wiki

If there's something that isn't clear, let me know and I'll add it.
