### ISSUE TITLE
Report as spam or spam+phishing

### ISSUE THREAD

**Issue by DSmidge** [justreportit/thunderbird#40]
Hi. It would be nice if there were 2 options in menu - "Report It as Spam" (to Spamcop and custom spam email addresses) and "Report It as Phishing" (for example to Spamcop and custom spam and phishing (for example reportphishing@apwg.org used by FF) email addresses.

**Comment by nicprov** [comment]
@DSmidge Adding the first option you requested (Spamcop and custom spam) is an interesting proposal as I'm aware not everyone wants to use the Registrar option. Though, I'm not sure the second option you requested is necessary (Spamcop and custom spam and phishing).

In this case, "reportphishing@apwg.org" can simply be added as a custom email address. 

Would this be ok like solution?

**Comment by DSmidge** [comment]
Sorry that I missed you comment. Now it is working perfectly.
