### ISSUE TITLE
...wants to report my domain as the spammer

### ISSUE THREAD

**Issue by glenstewart** [justreportit/thunderbird#41]
I suspect JustReportIt is confused by the Received headers in the email.  It wants to report my domain as the spammer, when the email To: field is in the same domain.  In my case, my email is routed from CloudFlare, which forwards it to a given address.

Perhaps a whitelist could be added, to force the plugin to look back to the earliest Received headers, because I also don't want to complain to my ISP or relay host for sending the spam either.

**Comment by nicprov** [comment]
I will be closing this because I have not received a response in several months. If it comes up again, simply re-create an issue through Github.
