### ISSUE TITLE
SpamCop will no longer accept email larger than 50.0K bytes

### ISSUE THREAD

**Issue by GitHubington** [justreportit/thunderbird#42]
Recently, reports suddenly stopped working... [SpamCop will no longer accept email larger than 50.0K bytes](https://www.spamcop.net/sc)

I manually found that attaching groups of messages (.eml) totalling 50k or less to Just Report It results in a successful report.

It would be good if Just Report It could automate this process.

**Comment by nicprov** [comment]
@GitHubington Thanks for highlighting this issue. I'll add this to the backlog as it's definitely an important issue to fix.

**Comment by xrat** [comment]
Thanks for adding the option to limit attachment size.

FTR: I am submitting to SpamCop via SMTP to `submit.<KEY>@spam.spamcop.net` and messages over 50k are accepted just fine.
