### ISSUE TITLE
Incorrect identity selected

### ISSUE THREAD

**Issue by aieri** [justreportit/thunderbird#49]
The extension seems to always select the first available identity, instead of the one belonging to the account that received the spam.
In my case, I have two email accounts configured in Thunderbird (let's call them A and B), and when I report an email delivered to the B account, the generated email pre-selects my A identity.

**Comment by nicprov** [comment]
@aieri Thanks for highlighting this! I am able to reproduce it on my side. I will mark this as a bug and will fix it in the next release!
