### ISSUE TITLE
Problem with Smart Folders (searches)

### ISSUE THREAD

**Issue by forrie** [justreportit/thunderbird#50]
I had a Smart Folder (saved search) in Thunderbird Supernova that collected all my Spam folders.  It's clunky, doesn't refresh consistently, etc., but I noticed that JustReportIt doesn't work on these, only on the real folders.   That could also be a technical limitation in how Thunderbird implements this feature.

I'm not entirely sure how other mailers implement Smart Folders, though.

**Comment by nicprov** [comment]
@forrie Unfortunately this is a technical limitation of Thunderbird.
