### ISSUE TITLE
Exiting the window accidentally X does not preserve a draft

### ISSUE THREAD

**Issue by forrie** [justreportit/thunderbird#51]
If you accidentally exit the window (X, on a Mac), the message disappears and there is no Draft stored.  Would it make sense to have this create a draft and send, then delete the draft as a normal Thunderbird email would?

**Comment by nicprov** [comment]
@forrie This seems to be a bug with [Thunderbird WebExtension API](https://webextension-api.thunderbird.net/en/stable/index.html).

I just tested this myself (on mac), and if I open a compose window (using the UI), add a message and try to close it, it prompts me to save the message as a draft. However, the same is not true when a compose window is created through the WebExtension API. This seems to be an inconsistency in the application, I will submit a bug with Thunderbird.
