### ISSUE TITLE
Feature / Bug: Spam Report message language is local, not English - no option to change it.

### ISSUE THREAD

**Issue by kkarhan** [justreportit/thunderbird#65]
### Problem:
I sadly miss any option to set the spam report message to be in English and not the System Language like German.

Not shure if said messages will be read if they ain't in English - tho at Spammers like GoDaddy that's always up for debate.
![Bildschirmfoto vom 2024-06-03 13-43-27](https://github.com/justreportit/thunderbird/assets/30401796/d2a375cc-df39-4762-b284-ae7d232d4e6e)

### Suggested Solution:
Make it default to English and add a toggle in the add-on setting to configure it in the meantime.

### Suggested Quick Workaround:
Name the config parameter in the "Advanced Settings" to set the reporting language [i.e. ```extensions.reportit.language``` with default being ```en-us``` so the addon can store and parse that setting...

##### Not to be confused with #7 .

Thanks for your time.

**Comment by kkarhan** [comment]
Cc: @nicprov ?

**Comment by nicprov** [comment]
@kkarhan I apologize for the delay, I don't always get notifications from Github for some reason. 

This seems like a pretty valid usecase. What I can do is add a menu option for attached messages, and give you the option to select either thunderbird language or english

**Comment by kkarhan** [comment]
Thanks fir fixing this! 
- Highly appreciated...
