### ISSUE TITLE
Add a method to use an alternative file extension for reports

### ISSUE THREAD

**Issue by dplmr** [justreportit/thunderbird#66]
When reporting spam, it creates an attachment of the original email called "message.eml".  Can you please add a feature to use an alternative file extension to eml? I would choose message.txt. 

This is because, attachments as .eml files are banned by some email providers. I get a bounce message that explains:

>    This message has been rejected because it has
>    a potentially executable attachment "message.eml"
>    This form of attachment has been used by
>    recent viruses or other malware.
>    If you meant to send this file then please
>    package it up as a zip file and resend it.

As a workaround, in the meantime, I have manually replaced instances of ".eml" with ".txt" in src/scripts/background.js.

**Comment by nicprov** [comment]
@dplmr I'll mark this as an enhancement. What I could do is add a menu option for the attached message, and give you the option to select .eml or .txt

**Comment by nicprov** [comment]
@dplmr This will be available in the next release: 
<img width="622" alt="image" src="https://github.com/user-attachments/assets/8c25d4ad-58f7-44c9-a8ba-b639150d7d5e">
