### ISSUE TITLE
Dark Theme - Override Colors Results In Unreadable Config

### ISSUE THREAD

**Issue by Ryushin** [justreportit/thunderbird#67]
When overriding the colors to create a dark theme, the Configuration is not readable:

![Override_Colors](https://github.com/justreportit/thunderbird/assets/4388558/3abad436-cdb4-4f9d-aae0-6ac976d05c69)
![Unreadable_Preferences](https://github.com/justreportit/thunderbird/assets/4388558/6ff46e59-06f7-42a7-b93f-6f06ef7f1a32)

Other extensions don't have a problem when overriding the colors.

**Comment by nicprov** [comment]
@Ryushin I'll label this issue as a bug, but it's a pretty niche scenario. Still, I will keep this issue open and will fix it when I get a chance.

**Comment by Ryushin** [comment]
> @Ryushin I'll label this issue as a bug, but it's a pretty niche scenario. Still, I will keep this issue open and will fix it when I get a chance.

Thanks, I appreciate it.

**Comment by nicprov** [comment]
@Ryushin I tried overriding the colors on my system but cannot seem to reproduce your issue. Take a look
<img width="560" alt="image" src="https://github.com/user-attachments/assets/5161ce38-ebde-417e-964f-a2bc76e36a38">
<img width="675" alt="image" src="https://github.com/user-attachments/assets/cdb3db2c-a907-4a8d-b4a4-29a2836de3c8">

What operating system and version of Thunderbird are you using?

**Comment by Ryushin** [comment]
Just upgraded to v128 of Thunderbird and it now appears to the same as yours.  So I guess the problem is solved.  Thank you for looking into it for me though.  I appreciate  your time.
