### ISSUE TITLE
SpamCop ID not saved properly

### ISSUE THREAD

**Issue by binarykitchen** [justreportit/thunderbird#68]
I think there is a bug. When you enter it, for example:
![image](https://github.com/justreportit/thunderbird/assets/177641/428646f4-f45c-4f1b-9809-0123f6ff91f3)

then use the tool to report, you can see weird double quotes:
![image](https://github.com/justreportit/thunderbird/assets/177641/19c7ec49-1c60-4ffc-94e8-614146bf69aa)

And when you go back and want to correct it, you can see it's gone:
![image](https://github.com/justreportit/thunderbird/assets/177641/f830df69-bfc6-4f2f-b115-56d6fea7381b)

Using latest version 3.1.1 here. Thanks for fixing this.

**Comment by nicprov** [comment]
@binarykitchen This is not a bug. In the description, it says to only put the SpamCopID (submit.{SpamCopID}@spam.spamcop.net). In the example you showed, you would only put 11111111111, or whatever your id is.

If you're still confused, feel free to email me: support@justreport.it
